# Generated by Django 4.2.2 on 2023-06-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_catagary',
            fields=[
                ('pcid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pcname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pdescription', models.TextField()),
                ('date', models.DateField()),
                ('pcname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_catagary')),
            ],
        ),
    ]
